config/routes.rb
Rails.application.routes.draw do
  # resources :activities do
  #   resources :comments
  # end
  
  resources :users do
    resources :comments
  end 

  resources :users do
    resources :activity_logs
  end

 
  
  resources :brainwaves do 
    resources :activities, only: [:show, :index]
  end
  
  resources :activities, only: [:index, :show, :new, :create, :edit, :update] do
     resources :activity_logs
  end

  resources :activity_logs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  
  
  
 
  # get '/auth/facebook/callback' => 'sessions#create'
  root 'sessions#welcome'
 
  get '/login', to: 'sessions#new', as: 'login'
  get '/auth/facebook/callback', to: 'sessions#facebook'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity_log.rb
class ActivityLog < ApplicationRecord
  belongs_to :user
  belongs_to :activity
  
  # scope :by_user, -> {where(user_id: current_user.id)}

  scope :created_before, ->(time) { where("created_at < ?", time)}

  scope :by_user, -> {where(user_id: user.id)}
end

app/controllers/activity_logs_controller.rb
class ActivityLogsController < ApplicationController
  
    
    def index
      @activities = current_user.activities
      # @activities = Activity.by_user
    end

    def show
     
      @activity = Activity.find(params[:activity_id])
      @activity_log = ActivityLog.find(params[:id])

    end

    def new
      @activity = Activity.find_by(params[:activity_id])
      @activity_log = ActivityLog.new
    end

    def create
      @activity_log = ActivityLog.new(params.require(:activity_log).permit(:duration, :user_id, :activity_id))
      @activity_log.user_id = current_user.id
     if  @activity_log.save
      redirect_to activity_logs_path
     else
      render :new
     end
    end

    def edit
      @activity = Activity.find_by(params[:activity_id])
      @activity_log = ActivityLog.find(params[:id])
    end

    def update
      @activity_log = ActivityLog.find(params[:id])
        @activity_log.update(activity_log_params)
        redirect_to user_activity_logs_path(current_user)
    end

    def destroy
      @activity_log = ActivityLog.find_by(params[:id]) 
      @activity_log.destroy
    
      redirect_to activity_logs_path
    end

end


private
def get_user
    @user = User.find_by(params[:user_id])
end

def activity_log_params
  params.require(:activity_log).permit(:duration, :user_id, :activity_id)
end

app/helpers/activity_logs_helper.rb
module ActivityLogsHelper
end

app/views/activity_logs/edit.html.erb
<h3> Edit Activity Form </h3>
<%= form_for @activity_log do |f| %>
    <div>   
    <%= f.collection_select(:activity_id, Activity.all, :id, :name, { prompt: @activity.name  }, class: "browser-default") %> <br/><br/>
<div>
    <div>
        <%= f.label :duration%>
        <%= f.text_field :duration%>
    </div>
         <%=f.submit "Submit"%>
    <%end %>

app/views/activity_logs/index.html.erb
<div class="section no-pad-bot" id="index-banner">
<div class="container">
  <h1 class="header center orange-text">My Activities</h1>
  <div class="row center">
    <h5 class="header col s12 light">Activities</h5>
  </div>
  </div>
  <div class="row center">
  <% @activities.each do |activity|%>
    <ul>
     <li><h2><%=activity.name%></h2></li>
    </ul>
    <%activity.activity_logs.each do |log|%>
      <ul>
        <li><%=log.duration%></li>
        <li><%=log.created_at%></li>
        <li><%=link_to "New Log", new_activity_activity_log_path(activity)%></li>
        <li><%= link_to "Edit  Log", edit_activity_log_path(log)%></li>
        <li><%= link_to "Delete Log", activity_log_path(log), method: :delete %></li>

      </ul>
    <%end%>
    </ul>
<% end %>
<div class="row center">
  <%= link_to "Try New Activity", new_activity_log_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
  <br><br>
</div>
</div>

app/views/activity_logs/new.html.erb
<h3> New Activity Log Form </h3>
<%= form_for  @activity_log do |f| %>

<div>   
    <%= f.collection_select(:activity_id, Activity.all, :id, :name, { prompt: 'Choose Activity' }, class: "browser-default") %> <br/><br/>
<div>
    <%= f.label :duration %>
    <%= f.text_field :duration %>
   
         <%=f.submit "Submit"%>
<%end %>

    

app/views/activity_logs/show.html.erb
<div class="section no-pad-bot" id="index-banner">
<div class="container">
  <br><br>
  <h1 class="header center orange-text"><%= @activity_log.activity.name %></h1>
  <div class="row center">
    <h5 class="header col s12 light"><%= @activity_log.duration %></h5>
  </div>