config/routes.rb
Rails.application.routes.draw do
  # resources :activities do
  #   resources :comments
  # end
  
  resources :users do
    resources :comments
  end 

  resources :users do
    resources :activity_logs
  end

 
  
  resources :brainwaves do 
    resources :activities, only: [:show, :index]
  end
  
  resources :activities, only: [:index, :show, :new, :create, :edit, :update] do
     resources :activity_logs
  end

  resources :activity_logs, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  
  
  
  
 
  # get '/auth/facebook/callback' => 'sessions#create'
  root 'sessions#welcome'
 
  get '/login', to: 'sessions#new', as: 'login'
  get '/auth/facebook/callback', to: 'sessions#facebook'
  post '/login', to: 'sessions#create'
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  delete '/logout', to: 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/activity.rb
class Activity < ApplicationRecord
    belongs_to :brainwave
    
    has_many :activity_logs
    has_many :users, through: :activity_logs
    
    validates_uniqueness_of :name

    

    scope :short_activities, -> { where("duration < 30")}

    # scope :long_activities, ->{ where("duration > 30")}

    scope :search, -> (term) {where("name LIKE ?", "%#{term}%") }

    scope :by_user, -> {joins(:activity_logs).where('activity_logs.user_id = ?')}
end
 

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
   

    def index
      
      @brainwave = Brainwave.find(params[:brainwave_id])
      if params[:term]
        @activities = @brainwave.activities.search(params[:term])
      elsif
        @activities = @brainwave.activities
      else
        @activities = Activity.all
      end
    
    end
  
          
    def show
      @brainwave = Brainwave.find(params[:brainwave_id])
      @activity = Activity.find(params[:id])
    end
  
    def new
        @activity = Activity.new
    end

    def destroy
      @activity = Activity.find_by_id(params[:id]) 
      @activity.destroy
    
      redirect_to activities_path
    end

  
    
    private
    
    def activity_params
        params.require(:activity).permit(:name, :duration, :category)
    end
  
  
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/index.html.erb
<div class="section no-pad-bot" id="index-banner">
<div class="container">
  <br><br>
  <h4> Search Activities </h4>
  <%= form_tag(brainwave_activities_path, method: "get") do %>
    <%= text_field_tag :term, nil,  id: "Search", placeholder: "enter search term" %>
  
    <%= submit_tag "Search"%>
  <% end %>
  <h1 class="header center orange-text">View  Different Activities to Train This Brainwave</h1>
  <div class="row center">
    <h5 class="header col s12 light">Activities</h5>
  </div>
  </div>
  <div class="row center">
  <% @activities.each do |a| %>
    <ul>
     <li><h2><%=link_to a.name, brainwave_activity_path(@brainwave, a.id)%></h2></li>
     <li><%= a.duration %></li>
     <l1><%= a.category %></li>
    </ul>
<% end %>
  <br><br>
</div>
</div>

app/views/activities/new.html.erb
<h1> New Activity </h1>
<h3> New Activity Form </h3>
<%= form_for @activity do |f| %>
    <div>
        <%= f.label :name%>
        <%= f.text_field :name%>
    </div>
    <div>
        <%= f.label :duration%>
        <%= f.text_field :duration%>
    </div>
    <div>
        <%= f.label :category%>
        <%= f.text_field :category%>
    </div>
    
   
         <%=f.submit "Submit"%>
    <%end %>

    

app/views/activities/show.html.erb
<div class="section no-pad-bot" id="index-banner">
<div class="container">
  <br><br>
  <h1 class="header center orange-text"><%= @activity.name%></h1>
  <div class="row center">
    <h5 class="header col s12 light"><%= @activity.category%></h5>
    <h6><%= link_to "Delete Post", activity_path(@activity), method: :delete %></h6>
  </div>
  <div class="row center">
  <%= link_to "Back To All Activities", brainwave_activities_path(@brainwave), :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
  </div>
  <br><br>
  <div class="row center">
  <%= link_to "Try New Activity", new_activity_log_path, :id => "download-button", :class => "btn-large waves-effect waves-light orange" %>
  <br><br>
</div>
</div>
</div>

   
 
  <br><br>
</div>
</div>